### ISSUE TITLE
  How to start the project?

### ISSUE THREAD

**Issue by IvansZ** [jschuur/streamers.dev#1]
hello!
run the "npm run dev",but it erorr :"Environment variable not found: DATABASE_URL."
can you tell me ,how run the project?

**Comment by jschuur** [comment]
Hi @IvansZ. The project needs environment variables set in a `.env` file based on the `.env.sample` file in the repo.

The database URL points to a PostgreSQL database that has been migrated via Prisma, and populated with channels to track. A backend server would need to periodically check the status of those channels and update the database too, and rebuild the JSON file on S3 for the initial page load.

It's not necessarily a project designed for other people to self-host their own instance, so there are no real setup instructions. It's primarily on GitHub so people might learn from some of the approaches I took and as a sample of my development work too.
